// AUTOGENERATED CODE: DO NOT EDIT - TODO Autogenerate again, because it's def been edited.

export const createTrellisActions = ({ getify, postify, putify, deletify }) => {
// /////////////////////////////////////////////////////////////////////////////
// Anchors API
// /////////////////////////////////////////////////////////////////////////////

  return {
    /**
     * CreateAnchor
     */
    CREATEANCHOR_URI: '/v1/editor/app/:appId/scene/:sceneId/anchor/foo',
    CREATEANCHOR: 'createanchor',
    createanchor: postify(CREATEANCHOR, CREATEANCHOR_URI),

    /**
     * UploadAnchor
     */
    UPLOADANCHOR_URI: '/v1/editor/app/:appId/scene/:sceneId/anchor/:anchorId',
    UPLOADANCHOR: 'uploadanchor',
    uploadanchor: putify(UPLOADANCHOR, UPLOADANCHOR_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // App API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetMyApps
     */
    GETMYAPPS_URI: '/v1/editor/app',
    GETMYAPPS: 'getmyapps',
    getmyapps: getify(GETMYAPPS, GETMYAPPS_URI),

    /**
     * GetApp
     */
    GETAPP_URI: '/v1/editor/app/:appId',
    GETAPP: 'getapp',
    getapp: getify(GETAPP, GETAPP_URI),

    /**
     * CreateApp
     */
    CREATEAPP_URI: '/v1/editor/app',
    CREATEAPP: 'createapp',
    createapp: postify(CREATEAPP, CREATEAPP_URI),

    /**
     * DuplicateApp
     */
    DUPLICATEAPP_URI: '/v1/editor/app',
    DUPLICATEAPP: 'duplicateapp',
    duplicateapp: postify(DUPLICATEAPP, DUPLICATEAPP_URI),

    /**
     * UpdateApp
     */
    UPDATEAPP_URI: '/v1/editor/app/:appId',
    UPDATEAPP: 'updateapp',
    updateapp: putify(UPDATEAPP, UPDATEAPP_URI),

    /**
     * DeleteApp
     */
    DELETEAPP_URI: '/v1/editor/app/:appId',
    DELETEAPP: 'deleteapp',
    deleteapp: deletify(DELETEAPP, DELETEAPP_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // AssetLibraries API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetAnAsset
     */
    GETANASSET_URI: '/v1/asset/:assetid',
    GETANASSET: 'getanasset',
    getanasset: getify(GETANASSET, GETANASSET_URI),

    /**
     * GetAppAssets
     */
    GETAPPASSETS_URI: '/v1/editor/app/:appId/library',
    GETAPPASSETS: 'getappassets',
    getappassets: getify(GETAPPASSETS, GETAPPASSETS_URI),

    /**
     * ShareAssetWithApp
     */
    SHAREASSETWITHAPP_URI: '/v1/editor/app/:appId/library',
    SHAREASSETWITHAPP: 'shareassetwithapp',
    shareassetwithapp: postify(SHAREASSETWITHAPP, SHAREASSETWITHAPP_URI),

    /**
     * GetPersonalAssets
     */
    GETPERSONALASSETS_URI: '/v1/user/:userid/library',
    GETPERSONALASSETS: 'getpersonalassets',
    getpersonalassets: getify(GETPERSONALASSETS, GETPERSONALASSETS_URI),

    /**
     * GetPublicAssets
     */
    GETPUBLICASSETS_URI: '/v1/library?tag=:tag',
    GETPUBLICASSETS: 'getpublicassets',
    getpublicassets: getify(GETPUBLICASSETS, GETPUBLICASSETS_URI),

    /**
     * UpdateAnAsset
     */
    UPDATEANASSET_URI: '/v1/asset/:assetid',
    UPDATEANASSET: 'updateanasset',
    updateanasset: putify(UPDATEANASSET, UPDATEANASSET_URI),

    /**
     * DeleteMyAsset
     */
    DELETEMYASSET_URI: '/v1/asset/:assetid',
    DELETEMYASSET: 'deletemyasset',
    deletemyasset: deletify(DELETEMYASSET, DELETEMYASSET_URI),

    /**
     * PromoteToStandard
     */
    PROMOTETOSTANDARD_URI: '/v1/library/standard',
    PROMOTETOSTANDARD: 'promotetostandard',
    promotetostandard: postify(PROMOTETOSTANDARD, PROMOTETOSTANDARD_URI),

    /**
     * DemoteToPersonal
     */
    DEMOTETOPERSONAL_URI: '/v1/user/:userid/library',
    DEMOTETOPERSONAL: 'demotetopersonal',
    demotetopersonal: postify(DEMOTETOPERSONAL, DEMOTETOPERSONAL_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Collaborators API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetAppCollaborators
     */
    GETAPPCOLLABORATORS_URI: '/v1/editor/app/:appId/collaborator',
    GETAPPCOLLABORATORS: 'getappcollaborators',
    getappcollaborators: getify(GETAPPCOLLABORATORS, GETAPPCOLLABORATORS_URI),

    /**
     * CreateAppCollaborator
     */
    CREATEAPPCOLLABORATOR_URI: '/v1/editor/app/:appId/collaborator',
    CREATEAPPCOLLABORATOR: 'createappcollaborator',
    createappcollaborator: postify(CREATEAPPCOLLABORATOR, CREATEAPPCOLLABORATOR_URI),

    /**
     * UpdateAppCollaborator
     */
    UPDATEAPPCOLLABORATOR_URI: '/v1/editor/app/:appId/collaborator/:secondaryCollaboratorId',
    UPDATEAPPCOLLABORATOR: 'updateappcollaborator',
    updateappcollaborator: putify(UPDATEAPPCOLLABORATOR, UPDATEAPPCOLLABORATOR_URI),

    /**
     * DeleteAppCollaborator
     */
    DELETEAPPCOLLABORATOR_URI: '/v1/editor/app/:appId/collaborator/:secondaryCollaboratorId',
    DELETEAPPCOLLABORATOR: 'deleteappcollaborator',
    deleteappcollaborator: deletify(DELETEAPPCOLLABORATOR, DELETEAPPCOLLABORATOR_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Devices API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetOrganizationDevices
     */
    GETORGANIZATIONDEVICES_URI: '/v1/org/:organizationId/device',
    GETORGANIZATIONDEVICES: 'getorganizationdevices',
    getorganizationdevices: getify(GETORGANIZATIONDEVICES, GETORGANIZATIONDEVICES_URI),

    /**
     * GetOrganizationDevice
     */
    GETORGANIZATIONDEVICE_URI: '/v1/org/:organizationId/device/:deviceId',
    GETORGANIZATIONDEVICE: 'getorganizationdevice',
    getorganizationdevice: getify(GETORGANIZATIONDEVICE, GETORGANIZATIONDEVICE_URI),

    /**
     * CreateOrganizationDevice
     */
    CREATEORGANIZATIONDEVICE_URI: '/v1/org/:organizationId/device',
    CREATEORGANIZATIONDEVICE: 'createorganizationdevice',
    createorganizationdevice: postify(CREATEORGANIZATIONDEVICE, CREATEORGANIZATIONDEVICE_URI),

    /**
     * UpdateOrganizationDevice
     */
    UPDATEORGANIZATIONDEVICE_URI: '/v1/org/:organizationId/device/:deviceId',
    UPDATEORGANIZATIONDEVICE: 'updateorganizationdevice',
    updateorganizationdevice: putify(UPDATEORGANIZATIONDEVICE, UPDATEORGANIZATIONDEVICE_URI),

    /**
     * DeleteOrganizationDevice
     */
    DELETEORGANIZATIONDEVICE_URI: '/v1/org/:organizationId/device/:deviceId',
    DELETEORGANIZATIONDEVICE: 'deleteorganizationdevice',
    deleteorganizationdevice: deletify(DELETEORGANIZATIONDEVICE, DELETEORGANIZATIONDEVICE_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // EmailAuth API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * EmailSignIn
     */
    EMAILSIGNIN_URI: '/v1/email/signin',
    EMAILSIGNIN: 'emailsignin',
    emailsignin: postify(EMAILSIGNIN, EMAILSIGNIN_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // File API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * CreateFile
     */
    CREATEFILE_URI: '/v1/file',
    CREATEFILE: 'createfile',
    createfile: postify(CREATEFILE, CREATEFILE_URI),

    /**
     * GetFile
     */
    GETFILE_URI: '/v1/file/:fileId',
    GETFILE: 'getfile',
    getfile: getify(GETFILE, GETFILE_URI),

    /**
     * GetMyFiles
     */
    GETMYFILES_URI: '/v1/file',
    GETMYFILES: 'getmyfiles',
    getmyfiles: getify(GETMYFILES, GETMYFILES_URI),

    /**
     * GetMyFilesByTags
     */
    GETMYFILESBYTAGS_URI: '/v1/file?tags=:tags',
    GETMYFILESBYTAGS: 'getmyfilesbytags',
    getmyfilesbytags: getify(GETMYFILESBYTAGS, GETMYFILESBYTAGS_URI),

    /**
     * UpdateFileInfo
     */
    UPDATEFILEINFO_URI: '/v1/file/:fileId',
    UPDATEFILEINFO: 'updatefileinfo',
    updatefileinfo: putify(UPDATEFILEINFO, UPDATEFILEINFO_URI),

    /**
     * UpdateFile
     */
    UPDATEFILE_URI: '/v1/file/:fileId',
    UPDATEFILE: 'updatefile',
    updatefile: putify(UPDATEFILE, UPDATEFILE_URI),

    /**
     * DeleteFile
     */
    DELETEFILE_URI: '/v1/file/:fileId',
    DELETEFILE: 'deletefile',
    deletefile: deletify(DELETEFILE, DELETEFILE_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // HoloAuth API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * HoloAuthorize
     */
    HOLOAUTHORIZE_URI: '/v1/holo/authorize',
    HOLOAUTHORIZE: 'holoauthorize',
    holoauthorize: postify(HOLOAUTHORIZE, HOLOAUTHORIZE_URI),

    /**
     * HoloSignin
     */
    HOLOSIGNIN_URI: '/v1/holo/signin',
    HOLOSIGNIN: 'holosignin',
    holosignin: postify(HOLOSIGNIN, HOLOSIGNIN_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Members API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * CreateMember
     */
    CREATEMEMBER_URI: '/v1/org/:organizationId/member',
    CREATEMEMBER: 'createmember',
    createmember: postify(CREATEMEMBER, CREATEMEMBER_URI),

    /**
     * GetAllOrganizationMembers
     */
    GETALLORGANIZATIONMEMBERS_URI: '/v1/org/:organizationId/member',
    GETALLORGANIZATIONMEMBERS: 'getallorganizationmembers',
    getallorganizationmembers: getify(GETALLORGANIZATIONMEMBERS, GETALLORGANIZATIONMEMBERS_URI),

    /**
     * GetOrganizationMember
     */
    GETORGANIZATIONMEMBER_URI: '/v1/org/:organizationId/member/:orgMemberId',
    GETORGANIZATIONMEMBER: 'getorganizationmember',
    getorganizationmember: getify(GETORGANIZATIONMEMBER, GETORGANIZATIONMEMBER_URI),

    /**
     * UpdateOrganizationMember
     */
    UPDATEORGANIZATIONMEMBER_URI: '/v1/org/:organizationId/member/:secondaryOrgMemberId',
    UPDATEORGANIZATIONMEMBER: 'updateorganizationmember',
    updateorganizationmember: putify(UPDATEORGANIZATIONMEMBER, UPDATEORGANIZATIONMEMBER_URI),

    /**
     * DeleteOrganizationMember
     */
    DELETEORGANIZATIONMEMBER_URI: '/v1/org/:organizationId/member/:secondaryOrgMemberId',
    DELETEORGANIZATIONMEMBER: 'deleteorganizationmember',
    deleteorganizationmember: deletify(DELETEORGANIZATIONMEMBER, DELETEORGANIZATIONMEMBER_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Neighborhoods API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetMyNeighborhoods
     */
    GETMYNEIGHBORHOODS_URI: '/v1/neighborhood',
    GETMYNEIGHBORHOODS: 'getmyneighborhoods',
    getmyneighborhoods: getify(GETMYNEIGHBORHOODS, GETMYNEIGHBORHOODS_URI),

    /**
     * GetNeighborhood
     */
    GETNEIGHBORHOOD_URI: '/v1/neighborhood/:neighborhoodId',
    GETNEIGHBORHOOD: 'getneighborhood',
    getneighborhood: getify(GETNEIGHBORHOOD, GETNEIGHBORHOOD_URI),

    /**
     * JoinNeighborhood
     */
    JOINNEIGHBORHOOD_URI: '/v1/neighborhood/:neighborhoodId/neighbor',
    JOINNEIGHBORHOOD: 'joinneighborhood',
    joinneighborhood: postify(JOINNEIGHBORHOOD, JOINNEIGHBORHOOD_URI),

    /**
     * GetNeighbors
     */
    GETNEIGHBORS_URI: '/v1/neighborhood/:neighborhoodId/neighbor',
    GETNEIGHBORS: 'getneighbors',
    getneighbors: getify(GETNEIGHBORS, GETNEIGHBORS_URI),

    /**
     * GetNeighbor
     */
    GETNEIGHBOR_URI: '/v1/neighborhood/:neighborhoodId/neighbor/:neighborId',
    GETNEIGHBOR: 'getneighbor',
    getneighbor: getify(GETNEIGHBOR, GETNEIGHBOR_URI),

    /**
     * GetNeighborhoodKvs
     */
    GETNEIGHBORHOODKVS_URI: '/v1/neighborhood/:neighborhoodId/kv',
    GETNEIGHBORHOODKVS: 'getneighborhoodkvs',
    getneighborhoodkvs: getify(GETNEIGHBORHOODKVS, GETNEIGHBORHOODKVS_URI),

    /**
     * GetNeighborhoodKv
     */
    GETNEIGHBORHOODKV_URI: '/v1/neighborhood/:neighborhoodId/kv/:neighborKvId',
    GETNEIGHBORHOODKV: 'getneighborhoodkv',
    getneighborhoodkv: getify(GETNEIGHBORHOODKV, GETNEIGHBORHOODKV_URI),

    /**
     * CreateNeighborhoodKv
     */
    CREATENEIGHBORHOODKV_URI: '/v1/neighborhood/:neighborhoodId/kv',
    CREATENEIGHBORHOODKV: 'createneighborhoodkv',
    createneighborhoodkv: postify(CREATENEIGHBORHOODKV, CREATENEIGHBORHOODKV_URI),

    /**
     * UpdateNeighborhoodKv
     */
    UPDATENEIGHBORHOODKV_URI: '/v1/neighborhood/:neighborhoodId/kv/:neighborKvId',
    UPDATENEIGHBORHOODKV: 'updateneighborhoodkv',
    updateneighborhoodkv: putify(UPDATENEIGHBORHOODKV, UPDATENEIGHBORHOODKV_URI),

    /**
     * DeleteNeighborhoodKv
     */
    DELETENEIGHBORHOODKV_URI: '/v1/neighborhood/:neighborhoodId/kv/:neighborKvId',
    DELETENEIGHBORHOODKV: 'deleteneighborhoodkv',
    deleteneighborhoodkv: deletify(DELETENEIGHBORHOODKV, DELETENEIGHBORHOODKV_URI),

    /**
     * CreateNeighborhood
     */
    CREATENEIGHBORHOOD_URI: '/v1/neighborhood',
    CREATENEIGHBORHOOD: 'createneighborhood',
    createneighborhood: postify(CREATENEIGHBORHOOD, CREATENEIGHBORHOOD_URI),

    /**
     * DeleteNeighborhood
     */
    DELETENEIGHBORHOOD_URI: '/v1/neighborhood/:neighborhoodId',
    DELETENEIGHBORHOOD: 'deleteneighborhood',
    deleteneighborhood: deletify(DELETENEIGHBORHOOD, DELETENEIGHBORHOOD_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Organizations API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * CreateOrganization
     */
    CREATEORGANIZATION_URI: '/v1/org',
    CREATEORGANIZATION: 'createorganization',
    createorganization: postify(CREATEORGANIZATION, CREATEORGANIZATION_URI),

    /**
     * GetMyOrganizations
     */
    GETMYORGANIZATIONS_URI: '/v1/org',
    GETMYORGANIZATIONS: 'getmyorganizations',
    getmyorganizations: getify(GETMYORGANIZATIONS, GETMYORGANIZATIONS_URI),

    /**
     * GetOrganization
     */
    GETORGANIZATION_URI: '/v1/org/:organizationId',
    GETORGANIZATION: 'getorganization',
    getorganization: getify(GETORGANIZATION, GETORGANIZATION_URI),

    /**
     * UpdateOrganization
     */
    UPDATEORGANIZATION_URI: '/v1/org/:organizationId',
    UPDATEORGANIZATION: 'updateorganization',
    updateorganization: putify(UPDATEORGANIZATION, UPDATEORGANIZATION_URI),

    /**
     * DeleteOrganization
     */
    DELETEORGANIZATION_URI: '/v1/org/:secondaryOrganizationId',
    DELETEORGANIZATION: 'deleteorganization',
    deleteorganization: deletify(DELETEORGANIZATION, DELETEORGANIZATION_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // PublishedApps API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetPublishedApp
     */
    GETPUBLISHEDAPP_URI: '/v1/app/:publicAppId',
    GETPUBLISHEDAPP: 'getpublishedapp',
    getpublishedapp: getify(GETPUBLISHEDAPP, GETPUBLISHEDAPP_URI),

    /**
     * GetPublishedScene
     */
    GETPUBLISHEDSCENE_URI: '/v1/app/:publicAppId/scene/:publicSceneId',
    GETPUBLISHEDSCENE: 'getpublishedscene',
    getpublishedscene: getify(GETPUBLISHEDSCENE, GETPUBLISHEDSCENE_URI),

    /**
     * GetPublishedAssets
     */
    GETPUBLISHEDASSETS_URI: '/v1/app/:publicAppId/asset',
    GETPUBLISHEDASSETS: 'getpublishedassets',
    getpublishedassets: getify(GETPUBLISHEDASSETS, GETPUBLISHEDASSETS_URI),

    /**
     * GetPublishedAsset
     */
    GETPUBLISHEDASSET_URI: '/v1/app/:publicAppId/asset/:publicAssetId',
    GETPUBLISHEDASSET: 'getpublishedasset',
    getpublishedasset: getify(GETPUBLISHEDASSET, GETPUBLISHEDASSET_URI),

    /**
     * GetPublishedAppScripts
     */
    GETPUBLISHEDAPPSCRIPTS_URI: '/v1/app/:publicAppId/script',
    GETPUBLISHEDAPPSCRIPTS: 'getpublishedappscripts',
    getpublishedappscripts: getify(GETPUBLISHEDAPPSCRIPTS, GETPUBLISHEDAPPSCRIPTS_URI),

    /**
     * GetPublishedScript
     */
    GETPUBLISHEDSCRIPT_URI: '/v1/app/:publicAppId/script/:publicScriptId',
    GETPUBLISHEDSCRIPT: 'getpublishedscript',
    getpublishedscript: getify(GETPUBLISHEDSCRIPT, GETPUBLISHEDSCRIPT_URI),

    /**
     * SearchPublishedApps
     */
    SEARCHPUBLISHEDAPPS_URI: '/v1/app?query=:query',
    SEARCHPUBLISHEDAPPS: 'searchpublishedapps',
    searchpublishedapps: getify(SEARCHPUBLISHEDAPPS, SEARCHPUBLISHEDAPPS_URI),

    /**
     * CreateMultiplayerToken
     */
    CREATEMULTIPLAYERTOKEN_URI: '/v1/app/:appId/token',
    CREATEMULTIPLAYERTOKEN: 'createmultiplayertoken',
    createmultiplayertoken: postify(CREATEMULTIPLAYERTOKEN, CREATEMULTIPLAYERTOKEN_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Scenes API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * CreateScene
     */
    CREATESCENE_URI: '/v1/editor/app/:appId/scene',
    CREATESCENE: 'createscene',
    createscene: postify(CREATESCENE, CREATESCENE_URI),

    /**
     * GetScene
     */
    GETSCENE_URI: '/v1/editor/app/:appId/scene/:sceneId',
    GETSCENE: 'getscene',
    getscene: getify(GETSCENE, GETSCENE_URI),

    /**
     * CreateSceneElement
     */
    CREATESCENEELEMENT_URI: '/v1/editor/app/:appId/scene/:sceneId',
    CREATESCENEELEMENT: 'createsceneelement',
    createsceneelement: putify(CREATESCENEELEMENT, CREATESCENEELEMENT_URI),

    /**
     * UpdateSceneElementString
     */
    UPDATESCENEELEMENTSTRING_URI: '/v1/editor/app/:appId/scene/:sceneId',
    UPDATESCENEELEMENTSTRING: 'updatesceneelementstring',
    updatesceneelementstring: putify(UPDATESCENEELEMENTSTRING, UPDATESCENEELEMENTSTRING_URI),

    /**
     * UpdateSceneElementInt
     */
    UPDATESCENEELEMENTINT_URI: '/v1/editor/app/:appId/scene/:sceneId',
    UPDATESCENEELEMENTINT: 'updatesceneelementint',
    updatesceneelementint: putify(UPDATESCENEELEMENTINT, UPDATESCENEELEMENTINT_URI),

    /**
     * UpdateSceneElementFloat
     */
    UPDATESCENEELEMENTFLOAT_URI: '/v1/editor/app/:appId/scene/:sceneId',
    UPDATESCENEELEMENTFLOAT: 'updatesceneelementfloat',
    updatesceneelementfloat: putify(UPDATESCENEELEMENTFLOAT, UPDATESCENEELEMENTFLOAT_URI),

    /**
     * UpdateSceneElementBool
     */
    UPDATESCENEELEMENTBOOL_URI: '/v1/editor/app/:appId/scene/:sceneId',
    UPDATESCENEELEMENTBOOL: 'updatesceneelementbool',
    updatesceneelementbool: putify(UPDATESCENEELEMENTBOOL, UPDATESCENEELEMENTBOOL_URI),

    /**
     * UpdateSceneElementVec3
     */
    UPDATESCENEELEMENTVEC3_URI: '/v1/editor/app/:appId/scene/:sceneId',
    UPDATESCENEELEMENTVEC3: 'updatesceneelementvec3',
    updatesceneelementvec3: putify(UPDATESCENEELEMENTVEC3, UPDATESCENEELEMENTVEC3_URI),

    /**
     * UpdateSceneElementCol4
     */
    UPDATESCENEELEMENTCOL4_URI: '/v1/editor/app/:appId/scene/:sceneId',
    UPDATESCENEELEMENTCOL4: 'updatesceneelementcol4',
    updatesceneelementcol4: putify(UPDATESCENEELEMENTCOL4, UPDATESCENEELEMENTCOL4_URI),

    /**
     * DeleteSceneElement
     */
    DELETESCENEELEMENT_URI: '/v1/editor/app/:appId/scene/:sceneId',
    DELETESCENEELEMENT: 'deletesceneelement',
    deletesceneelement: putify(DELETESCENEELEMENT, DELETESCENEELEMENT_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // ScriptLibraries API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetAppScripts
     */
    GETAPPSCRIPTS_URI: '/v1/app/:appId/script-library',
    GETAPPSCRIPTS: 'getappscripts',
    getappscripts: getify(GETAPPSCRIPTS, GETAPPSCRIPTS_URI),

    /**
     * GetPersonalScripts
     */
    GETPERSONALSCRIPTS_URI: '/v1/user/:userid/script-library',
    GETPERSONALSCRIPTS: 'getpersonalscripts',
    getpersonalscripts: getify(GETPERSONALSCRIPTS, GETPERSONALSCRIPTS_URI),

    /**
     * GetScript
     */
    GETSCRIPT_URI: '/v1/script/:scriptId',
    GETSCRIPT: 'getscript',
    getscript: getify(GETSCRIPT, GETSCRIPT_URI),

    /**
     * GetPublicScripts
     */
    GETPUBLICSCRIPTS_URI: '/v1/script-library?tag=:tag',
    GETPUBLICSCRIPTS: 'getpublicscripts',
    getpublicscripts: getify(GETPUBLICSCRIPTS, GETPUBLICSCRIPTS_URI),

    /**
     * CreateScript
     */
    CREATESCRIPT_URI: '/v1/script',
    CREATESCRIPT: 'createscript',
    createscript: postify(CREATESCRIPT, CREATESCRIPT_URI),

    /**
     * UpdateScript
     */
    UPDATESCRIPT_URI: '/v1/script/:scriptId',
    UPDATESCRIPT: 'updatescript',
    updatescript: putify(UPDATESCRIPT, UPDATESCRIPT_URI),

    /**
     * DeleteScript
     */
    DELETESCRIPT_URI: '/v1/script/:scriptId',
    DELETESCRIPT: 'deletescript',
    deletescript: deletify(DELETESCRIPT, DELETESCRIPT_URI),

    /**
     * ShareScriptWithApp
     */
    SHARESCRIPTWITHAPP_URI: '/v1/app/:appId/script-library',
    SHARESCRIPTWITHAPP: 'sharescriptwithapp',
    sharescriptwithapp: postify(SHARESCRIPTWITHAPP, SHARESCRIPTWITHAPP_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Snaps API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * CreateSnap
     */
    CREATESNAP_URI: '/v1/org/:organizationId/snap/:instanceId',
    CREATESNAP: 'createsnap',
    createsnap: postify(CREATESNAP, CREATESNAP_URI),

    /**
     * TriggerSnap
     */
    TRIGGERSNAP_URI: '/v1/org/:organizationId/snap/:instanceId',
    TRIGGERSNAP: 'triggersnap',
    triggersnap: putify(TRIGGERSNAP, TRIGGERSNAP_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Spaces API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * FindSpaces
     */
    FINDSPACES_URI: '/v1/editor/space?name=:name&owner=:owner',
    FINDSPACES: 'findspaces',
    findspaces: getify(FINDSPACES, FINDSPACES_URI),

    /**
     * CreateSpace
     */
    CREATESPACE_URI: '/v1/editor/space',
    CREATESPACE: 'createspace',
    createspace: postify(CREATESPACE, CREATESPACE_URI),

    /**
     * GetSpace
     */
    GETSPACE_URI: '/v1/editor/space/:spaceId',
    GETSPACE: 'getspace',
    getspace: getify(GETSPACE, GETSPACE_URI),

    /**
     * UpdateSpace
     */
    UPDATESPACE_URI: '/v1/editor/space/:spaceId',
    UPDATESPACE: 'updatespace',
    updatespace: putify(UPDATESPACE, UPDATESPACE_URI),

    /**
     * DeleteSpace
     */
    DELETESPACE_URI: '/v1/editor/space/:spaceId',
    DELETESPACE: 'deletespace',
    deletespace: deletify(DELETESPACE, DELETESPACE_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Storage API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetAllKvs
     */
    GETALLKVS_URI: '/v1/kv',
    GETALLKVS: 'getallkvs',
    getallkvs: getify(GETALLKVS, GETALLKVS_URI),

    /**
     * GetAllKvHeaders
     */
    GETALLKVHEADERS_URI: '/v1/kv?headers=true',
    GETALLKVHEADERS: 'getallkvheaders',
    getallkvheaders: getify(GETALLKVHEADERS, GETALLKVHEADERS_URI),

    /**
     * CreateKv
     */
    CREATEKV_URI: '/v1/kv',
    CREATEKV: 'createkv',
    createkv: postify(CREATEKV, CREATEKV_URI),

    /**
     * GetKv
     */
    GETKV_URI: '/v1/kv/:kvid',
    GETKV: 'getkv',
    getkv: getify(GETKV, GETKV_URI),

    /**
     * DeleteKv
     */
    DELETEKV_URI: '/v1/kv/:kvid',
    DELETEKV: 'deletekv',
    deletekv: deletify(DELETEKV, DELETEKV_URI),

    /**
     * UpdateKv
     */
    UPDATEKV_URI: '/v1/kv/:kvid',
    UPDATEKV: 'updatekv',
    updatekv: putify(UPDATEKV, UPDATEKV_URI),

    /**
     * GetAllKvsBytag
     */
    GETALLKVSBYTAG_URI: '/v1/kv?tags=:tags',
    GETALLKVSBYTAG: 'getallkvsbytag',
    getallkvsbytag: getify(GETALLKVSBYTAG, GETALLKVSBYTAG_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // User API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetUser
     */
    GETUSER_URI: '/v1/user/:userid',
    GETUSER: 'getuser',
    getuser: getify(GETUSER, GETUSER_URI),

    /**
     * SearchUsersById
     */
    SEARCHUSERSBYID_URI: '/v1/user?id=:id',
    SEARCHUSERSBYID: 'searchusersbyid',
    searchusersbyid: getify(SEARCHUSERSBYID, SEARCHUSERSBYID_URI),

    /**
     * SearchUsersByEmail
     */
    SEARCHUSERSBYEMAIL_URI: '/v1/user?email=:email',
    SEARCHUSERSBYEMAIL: 'searchusersbyemail',
    searchusersbyemail: getify(SEARCHUSERSBYEMAIL, SEARCHUSERSBYEMAIL_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Utilities API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * SendEmail
     */
    SENDEMAIL_URI: '/v1/utilities/sendmail',
    SENDEMAIL: 'sendemail',
    sendemail: postify(SENDEMAIL, SENDEMAIL_URI),

    /**
     * GettingStarted
     */
    GETTINGSTARTED_URI: '/v1/getstarted',
    GETTINGSTARTED: 'gettingstarted',
    gettingstarted: postify(GETTINGSTARTED, GETTINGSTARTED_URI),

    // /////////////////////////////////////////////////////////////////////////////
    // Versioning API
    // /////////////////////////////////////////////////////////////////////////////

    /**
     * GetApiVersion
     */
    GETAPIVERSION_URI: '/v1/versions/api',
    GETAPIVERSION: 'getapiversion',
    getapiversion: getify(GETAPIVERSION, GETAPIVERSION_URI),

    /**
     * GetHololensVersion
     */
    GETHOLOLENSVERSION_URI: '/v1/versions/hololens',
    GETHOLOLENSVERSION: 'gethololensversion',
    gethololensversion: getify(GETHOLOLENSVERSION, GETHOLOLENSVERSION_URI),

    /**
     * GetWebVersion
     */
    GETWEBVERSION_URI: '/v1/versions/web',
    GETWEBVERSION: 'getwebversion',
    getwebversion: getify(GETWEBVERSION, GETWEBVERSION_URI)
  }
};
