
// AUTOGENERATED CODE: DO NOT EDIT
import { getify, postify, putify, deletify } from './actions';

///////////////////////////////////////////////////////////////////////////////
// AuthSMS API
///////////////////////////////////////////////////////////////////////////////

/**
 * Start
 */
const START_URI = '/v1/auth/sms/start';
export const START = 'start';
export const start = postify(START, START_URI);

/**
 * Verify
 */
const VERIFY_URI = '/v1/auth/sms/verify';
export const VERIFY = 'verify';
export const verify = postify(VERIFY, VERIFY_URI);

///////////////////////////////////////////////////////////////////////////////
// AuthEmail API
///////////////////////////////////////////////////////////////////////////////

/**
 * EmailSignup
 */
const EMAILSIGNUP_URI = '/v1/auth/email/signup';
export const EMAILSIGNUP = 'emailsignup';
export const emailsignup = postify(EMAILSIGNUP, EMAILSIGNUP_URI);

/**
 * EmailSignin
 */
const EMAILSIGNIN_URI = '/v1/auth/email/signin';
export const EMAILSIGNIN = 'emailsignin';
export const emailsignin = postify(EMAILSIGNIN, EMAILSIGNIN_URI);

///////////////////////////////////////////////////////////////////////////////
// AdminSMS API
///////////////////////////////////////////////////////////////////////////////

/**
 * VerifiedSendSms
 */
const VERIFIEDSENDSMS_URI = '/v1/admin/sms/verifiedSend';
export const VERIFIEDSENDSMS = 'verifiedsendsms';
export const verifiedsendsms = postify(VERIFIEDSENDSMS, VERIFIEDSENDSMS_URI);

/**
 * BlockSmsNumber
 */
const BLOCKSMSNUMBER_URI = '/v1/admin/sms/blockNumber';
export const BLOCKSMSNUMBER = 'blocksmsnumber';
export const blocksmsnumber = postify(BLOCKSMSNUMBER, BLOCKSMSNUMBER_URI);

/**
 * UnblockSmsNumber
 */
const UNBLOCKSMSNUMBER_URI = '/v1/admin/sms/unblockNumber';
export const UNBLOCKSMSNUMBER = 'unblocksmsnumber';
export const unblocksmsnumber = postify(UNBLOCKSMSNUMBER, UNBLOCKSMSNUMBER_URI);

/**
 * ResetSmsVerifyStatus
 */
const RESETSMSVERIFYSTATUS_URI = '/v1/admin/sms/resetVerifyStatus';
export const RESETSMSVERIFYSTATUS = 'resetsmsverifystatus';
export const resetsmsverifystatus = postify(RESETSMSVERIFYSTATUS, RESETSMSVERIFYSTATUS_URI);

///////////////////////////////////////////////////////////////////////////////
// Snaps API
///////////////////////////////////////////////////////////////////////////////

/**
 * Create
 */
const CREATE_URI = '/v1/snaps/create';
export const CREATE = 'create';
export const create = postify(CREATE, CREATE_URI);

/**
 * Snaps
 */
const SNAPS_URI = '/v1/snaps?limit=:limit';
export const SNAPS = 'snaps';
export const snaps = getify(SNAPS, SNAPS_URI);

/**
 * Snap
 */
const SNAP_URI = '/v1/snaps/:id';
export const SNAP = 'snap';
export const snap = getify(SNAP, SNAP_URI);

/**
 * SendSnap
 */
const SENDSNAP_URI = '/v1/snaps/:id';
export const SENDSNAP = 'sendsnap';
export const sendsnap = putify(SENDSNAP, SENDSNAP_URI);

///////////////////////////////////////////////////////////////////////////////
// User API
///////////////////////////////////////////////////////////////////////////////

/**
 * GetUser
 */
const GETUSER_URI = '/v1/users/:userId';
export const GETUSER = 'getuser';
export const getuser = getify(GETUSER, GETUSER_URI);

/**
 * GetUsers
 */
const GETUSERS_URI = '/v1/users/getUsers';
export const GETUSERS = 'getusers';
export const getusers = postify(GETUSERS, GETUSERS_URI);
