// AUTOGENERATED CODE: DO NOT EDIT

// /////////////////////////////////////////////////////////////////////////////
// URIs
// /////////////////////////////////////////////////////////////////////////////

// User
const GETUSER_URI = '/v1/user/:userid';
const SEARCHUSERSBYID_URI = '/v1/user';
const SEARCHUSERSBYEMAIL_URI = '/v1/user';

// Versioning
const GETAPIVERSION_URI = '/v1/versions/api';
const GETHOLOLENSVERSION_URI = '/v1/versions/hololens';
const GETWEBVERSION_URI = '/v1/versions/web';

// Email Auth
const EMAILSIGNIN_URI = '/v1/email/signin';

// Holo Auth
const HOLOAUTHORIZE_URI = '/v1/holo/authorize';
const HOLOSIGNIN_URI = '/v1/holo/signin';

// Organizations
const CREATEORGANIZATION_URI = '/v1/org';
const GETMYORGANIZATIONS_URI = '/v1/org';
const GETORGANIZATION_URI = '/v1/org/:organizationId';
const UPDATEORGANIZATION_URI = '/v1/org/:organizationId';
const DELETEORGANIZATION_URI = '/v1/org/:secondaryOrganizationId';

// Members
const CREATEMEMBER_URI = '/v1/org/:organizationId/member';
const GETALLORGANIZATIONMEMBERS_URI = '/v1/org/:organizationId/member';
const GETORGANIZATIONMEMBER_URI = '/v1/org/:organizationId/member/{{orgMemberId}}';
const UPDATEORGANIZATIONMEMBER_URI = '/v1/org/:organizationId/member/{{secondaryOrgMemberId}}';
const DELETEORGANIZATIONMEMBER_URI = '/v1/org/:organizationId/member/{{secondaryOrgMemberId}}';

// Devices
const GETORGANIZATIONDEVICES_URI = '/v1/org/:organizationId/device';
const GETORGANIZATIONDEVICE_URI = '/v1/org/:organizationId/device/{{deviceId}}';
const CREATEORGANIZATIONDEVICE_URI = '/v1/org/:organizationId/device';
const UPDATEORGANIZATIONDEVICE_URI = '/v1/org/:organizationId/device/{{deviceId}}';
const DELETEORGANIZATIONDEVICE_URI = '/v1/org/:organizationId/device/{{deviceId}}';

// Snaps
const CREATESNAP_URI = '/v1/org/744d26da-959d-48ce-93b7-ec1071b39e24/snap/foo';
const TRIGGERSNAP_URI = '/v1/org/:organizationId/snap/{{instanceId}}';

// Utilities
const SENDEMAIL_URI = '/v1/utilities/sendmail';
const GETTINGSTARTED_URI = '/v1/getstarted';

// Storage
const GETALLKVS_URI = '/v1/kv';
const GETALLKVHEADERS_URI = '/v1/kv';
const CREATEKV_URI = '/v1/kv';
const GETKV_URI = '/v1/kv/:kvid';
const DELETEKV_URI = '/v1/kv/:kvid';
const UPDATEKV_URI = '/v1/kv/:kvid';
const GETALLKVSBYTAG_URI = '/v1/kv';

// Neighborhoods
const GETMYNEIGHBORHOODS_URI = '/v1/neighborhood';
const GETNEIGHBORHOOD_URI = '/v1/neighborhood/:neighborhoodId';
const JOINNEIGHBORHOOD_URI = '/v1/neighborhood/:neighborhoodId/neighbor';
const GETNEIGHBORS_URI = '/v1/neighborhood/:neighborhoodId/neighbor';
const GETNEIGHBOR_URI = '/v1/neighborhood/:neighborhoodId/neighbor/{{neighborId}}';
const GETNEIGHBORHOODKVS_URI = '/v1/neighborhood/:neighborhoodId/kv';
const GETNEIGHBORHOODKV_URI = '/v1/neighborhood/:neighborhoodId/kv/{{neighborKvId}}';
const CREATENEIGHBORHOODKV_URI = '/v1/neighborhood/:neighborhoodId/kv';
const UPDATENEIGHBORHOODKV_URI = '/v1/neighborhood/:neighborhoodId/kv/{{neighborKvId}}';
const DELETENEIGHBORHOODKV_URI = '/v1/neighborhood/:neighborhoodId/kv/{{neighborKvId}}';
const CREATENEIGHBORHOOD_URI = '/v1/neighborhood';
const DELETENEIGHBORHOOD_URI = '/v1/neighborhood/:neighborhoodId';

// File
const CREATEFILE_URI = '/v1/file';
const GETFILE_URI = '/v1/file/:fileId';
const GETMYFILES_URI = '/v1/file';
const GETMYFILESBYTAGS_URI = '/v1/file';
const UPDATEFILEINFO_URI = '/v1/file/:fileId';
const UPDATEFILE_URI = '/v1/file/:fileId';
const DELETEFILE_URI = '/v1/file/:fileId';

// App
const GETMYAPPS_URI = '/v1/editor/app';
const GETAPP_URI = '/v1/editor/app/:appId';
const CREATEAPP_URI = '/v1/editor/app';
const DUPLICATEAPP_URI = '/v1/editor/app';
const UPDATEAPP_URI = '/v1/editor/app/:appId';
const DELETEAPP_URI = '/v1/editor/app/:appId';

// Anchors
const CREATEANCHOR_URI = '/v1/editor/app/:appId/scene/{{sceneId}}/anchor/foo';
const UPLOADANCHOR_URI = '/v1/editor/app/:appId/scene/{{sceneId}}/anchor/{{anchorId}}';

// Collaborators
const GETAPPCOLLABORATORS_URI = '/v1/editor/app/:appId/collaborator';
const CREATEAPPCOLLABORATOR_URI = '/v1/editor/app/:appId/collaborator';
const UPDATEAPPCOLLABORATOR_URI = '/v1/editor/app/:appId/collaborator/{{secondaryCollaboratorId}}';
const DELETEAPPCOLLABORATOR_URI = '/v1/editor/app/:appId/collaborator/{{secondaryCollaboratorId}}';

// Scenes
const CREATESCENE_URI = '/v1/editor/app/:appId/scene';
const GETSCENE_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const CREATESCENEELEMENT_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const UPDATESCENEELEMENTSTRING_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const UPDATESCENEELEMENTINT_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const UPDATESCENEELEMENTFLOAT_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const UPDATESCENEELEMENTBOOL_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const UPDATESCENEELEMENTVEC3_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const UPDATESCENEELEMENTCOL4_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';
const DELETESCENEELEMENT_URI = '/v1/editor/app/:appId/scene/{{sceneId}}';

// Asset Libraries
const GETANASSET_URI = '/v1/asset/:assetid';
const GETAPPASSETS_URI = '/v1/editor/app/:appId/library';
const SHAREASSETWITHAPP_URI = '/v1/editor/app/:appId/library';
const GETPERSONALASSETS_URI = '/v1/user/:userid/library';
const GETPUBLICASSETS_URI = '/v1/library';
const UPDATEANASSET_URI = '/v1/asset/:assetid';
const DELETEMYASSET_URI = '/v1/asset/:assetid';
const PROMOTETOSTANDARD_URI = '/v1/library/standard';
const DEMOTETOPERSONAL_URI = '/v1/user/:userid/library';

// Script Libraries
const GETAPPSCRIPTS_URI = '/v1/app/:appId/script-library';
const GETPERSONALSCRIPTS_URI = '/v1/user/:userid/script-library';
const GETPUBLICSCRIPTS_URI = '/v1/script-library';
const GETSCRIPT_URI = '/v1/script/:scriptId';
const CREATESCRIPT_URI = '/v1/script';
const UPDATESCRIPT_URI = '/v1/script/:scriptId';
const DELETESCRIPT_URI = '/v1/script/:scriptId';
const SHARESCRIPTWITHAPP_URI = '/v1/app/:appId/script-library';

// Published Apps
const GETPUBLISHEDAPP_URI = '/v1/app/:publicAppId';
const GETPUBLISHEDSCENE_URI = '/v1/app/:publicAppId/scene/{{publicSceneId}}';
const GETPUBLISHEDASSETS_URI = '/v1/app/:publicAppId/asset';
const GETPUBLISHEDASSET_URI = '/v1/app/:publicAppId/asset/{{publicAssetId}}';
const GETPUBLISHEDAPPSCRIPTS_URI = '/v1/app/:publicAppId/script';
const GETPUBLISHEDSCRIPT_URI = '/v1/app/:publicAppId/script/{{publicScriptId}}';
const SEARCHPUBLISHEDAPPS_URI = '/v1/app';
const CREATEMULTIPLAYERTOKEN_URI = '/v1/app/:appId/token';

// Spaces
const FINDSPACES_URI = '/v1/editor/space';
const CREATESPACE_URI = '/v1/editor/space';
const GETSPACE_URI = '/v1/editor/space/:spaceId';
const UPDATESPACE_URI = '/v1/editor/space/:spaceId';
const UPDATESPACEVALUE_URI = '/v1/editor/space/:spaceId';
const DELETESPACE_URI = '/v1/editor/space/:spaceId';

// /////////////////////////////////////////////////////////////////////////////
// ACTION TYPES
// /////////////////////////////////////////////////////////////////////////////

// User
export const GETUSER = 'getuser';
export const SEARCHUSERSBYID = 'searchusersbyid';
export const SEARCHUSERSBYEMAIL = 'searchusersbyemail';

// Versioning
export const GETAPIVERSION = 'getapiversion';
export const GETHOLOLENSVERSION = 'gethololensversion';
export const GETWEBVERSION = 'getwebversion';

// Email Auth
export const EMAILSIGNIN = 'emailsignin';

// Holo Auth
export const HOLOAUTHORIZE = 'holoauthorize';
export const HOLOSIGNIN = 'holosignin';

// Organizations
export const CREATEORGANIZATION = 'createorganization';
export const GETMYORGANIZATIONS = 'getmyorganizations';
export const GETORGANIZATION = 'getorganization';
export const UPDATEORGANIZATION = 'updateorganization';
export const DELETEORGANIZATION = 'deleteorganization';

// Members
export const CREATEMEMBER = 'createmember';
export const GETALLORGANIZATIONMEMBERS = 'getallorganizationmembers';
export const GETORGANIZATIONMEMBER = 'getorganizationmember';
export const UPDATEORGANIZATIONMEMBER = 'updateorganizationmember';
export const DELETEORGANIZATIONMEMBER = 'deleteorganizationmember';

// Devices
export const GETORGANIZATIONDEVICES = 'getorganizationdevices';
export const GETORGANIZATIONDEVICE = 'getorganizationdevice';
export const CREATEORGANIZATIONDEVICE = 'createorganizationdevice';
export const UPDATEORGANIZATIONDEVICE = 'updateorganizationdevice';
export const DELETEORGANIZATIONDEVICE = 'deleteorganizationdevice';

// Snaps
export const CREATESNAP = 'createsnap';
export const TRIGGERSNAP = 'triggersnap';

// Utilities
export const SENDEMAIL = 'sendemail';
export const GETTINGSTARTED = 'gettingstarted';

// Storage
export const GETALLKVS = 'getallkvs';
export const GETALLKVHEADERS = 'getallkvheaders';
export const CREATEKV = 'createkv';
export const GETKV = 'getkv';
export const DELETEKV = 'deletekv';
export const UPDATEKV = 'updatekv';
export const GETALLKVSBYTAG = 'getallkvsbytag';

// Neighborhoods
export const GETMYNEIGHBORHOODS = 'getmyneighborhoods';
export const GETNEIGHBORHOOD = 'getneighborhood';
export const JOINNEIGHBORHOOD = 'joinneighborhood';
export const GETNEIGHBORS = 'getneighbors';
export const GETNEIGHBOR = 'getneighbor';
export const GETNEIGHBORHOODKVS = 'getneighborhoodkvs';
export const GETNEIGHBORHOODKV = 'getneighborhoodkv';
export const CREATENEIGHBORHOODKV = 'createneighborhoodkv';
export const UPDATENEIGHBORHOODKV = 'updateneighborhoodkv';
export const DELETENEIGHBORHOODKV = 'deleteneighborhoodkv';
export const CREATENEIGHBORHOOD = 'createneighborhood';
export const DELETENEIGHBORHOOD = 'deleteneighborhood';

// File
export const CREATEFILE = 'createfile';
export const GETFILE = 'getfile';
export const GETMYFILES = 'getmyfiles';
export const GETMYFILESBYTAGS = 'getmyfilesbytags';
export const UPDATEFILEINFO = 'updatefileinfo';
export const UPDATEFILE = 'updatefile';
export const DELETEFILE = 'deletefile';

// App
export const GETMYAPPS = 'getmyapps';
export const GETAPP = 'getapp';
export const CREATEAPP = 'createapp';
export const DUPLICATEAPP = 'duplicateapp';
export const UPDATEAPP = 'updateapp';
export const DELETEAPP = 'deleteapp';

// Anchors
export const CREATEANCHOR = 'createanchor';
export const UPLOADANCHOR = 'uploadanchor';

// Collaborators
export const GETAPPCOLLABORATORS = 'getappcollaborators';
export const CREATEAPPCOLLABORATOR = 'createappcollaborator';
export const UPDATEAPPCOLLABORATOR = 'updateappcollaborator';
export const DELETEAPPCOLLABORATOR = 'deleteappcollaborator';

// Scenes
export const CREATESCENE = 'createscene';
export const GETSCENE = 'getscene';
export const CREATESCENEELEMENT = 'createsceneelement';
export const UPDATESCENEELEMENTSTRING = 'updatesceneelementstring';
export const UPDATESCENEELEMENTINT = 'updatesceneelementint';
export const UPDATESCENEELEMENTFLOAT = 'updatesceneelementfloat';
export const UPDATESCENEELEMENTBOOL = 'updatesceneelementbool';
export const UPDATESCENEELEMENTVEC3 = 'updatesceneelementvec3';
export const UPDATESCENEELEMENTCOL4 = 'updatesceneelementcol4';
export const DELETESCENEELEMENT = 'deletesceneelement';

// Asset Libraries
export const GETANASSET = 'getanasset';
export const GETAPPASSETS = 'getappassets';
export const SHAREASSETWITHAPP = 'shareassetwithapp';
export const GETPERSONALASSETS = 'getpersonalassets';
export const GETPUBLICASSETS = 'getpublicassets';
export const UPDATEANASSET = 'updateanasset';
export const DELETEMYASSET = 'deletemyasset';
export const PROMOTETOSTANDARD = 'promotetostandard';
export const DEMOTETOPERSONAL = 'demotetopersonal';

// Script Libraries
export const GETAPPSCRIPTS = 'getappscripts';
export const GETPERSONALSCRIPTS = 'getpersonalscripts';
export const GETPUBLICSCRIPTS = 'getpublicscripts';
export const GETSCRIPT = 'getscript';
export const CREATESCRIPT = 'createscript';
export const UPDATESCRIPT = 'updatescript';
export const DELETESCRIPT = 'deletescript';
export const SHARESCRIPTWITHAPP = 'sharescriptwithapp';

// Published Apps
export const GETPUBLISHEDAPP = 'getpublishedapp';
export const GETPUBLISHEDSCENE = 'getpublishedscene';
export const GETPUBLISHEDASSETS = 'getpublishedassets';
export const GETPUBLISHEDASSET = 'getpublishedasset';
export const GETPUBLISHEDAPPSCRIPTS = 'getpublishedappscripts';
export const GETPUBLISHEDSCRIPT = 'getpublishedscript';
export const SEARCHPUBLISHEDAPPS = 'searchpublishedapps';
export const CREATEMULTIPLAYERTOKEN = 'createmultiplayertoken';

// Spaces
export const FINDSPACES = 'findspaces';
export const CREATESPACE = 'createspace';
export const GETSPACE = 'getspace';
export const UPDATESPACE = 'updatespace';
export const UPDATESPACEVALUE = 'updatespacevalue';
export const DELETESPACE = 'deletespace';

// /////////////////////////////////////////////////////////////////////////////
// ACTIONS
// /////////////////////////////////////////////////////////////////////////////
export const createActions = ({ getify, postify, putify, deletify }) => ({
    _targetName: 'trellis',

    // User
    getuser: getify(GETUSER, GETUSER_URI),
    searchusersbyid: getify(SEARCHUSERSBYID, SEARCHUSERSBYID_URI),
    searchusersbyemail: getify(SEARCHUSERSBYEMAIL, SEARCHUSERSBYEMAIL_URI),

    // Versioning
    getapiversion: getify(GETAPIVERSION, GETAPIVERSION_URI),
    gethololensversion: getify(GETHOLOLENSVERSION, GETHOLOLENSVERSION_URI),
    getwebversion: getify(GETWEBVERSION, GETWEBVERSION_URI),

    // Email Auth
    emailsignin: postify(EMAILSIGNIN, EMAILSIGNIN_URI),

    // Holo Auth
    holoauthorize: postify(HOLOAUTHORIZE, HOLOAUTHORIZE_URI),
    holosignin: postify(HOLOSIGNIN, HOLOSIGNIN_URI),

    // Organizations
    createorganization: postify(CREATEORGANIZATION, CREATEORGANIZATION_URI),
    getmyorganizations: getify(GETMYORGANIZATIONS, GETMYORGANIZATIONS_URI),
    getorganization: getify(GETORGANIZATION, GETORGANIZATION_URI),
    updateorganization: putify(UPDATEORGANIZATION, UPDATEORGANIZATION_URI),
    deleteorganization: deletify(DELETEORGANIZATION, DELETEORGANIZATION_URI),

    // Members
    createmember: postify(CREATEMEMBER, CREATEMEMBER_URI),
    getallorganizationmembers: getify(GETALLORGANIZATIONMEMBERS, GETALLORGANIZATIONMEMBERS_URI),
    getorganizationmember: getify(GETORGANIZATIONMEMBER, GETORGANIZATIONMEMBER_URI),
    updateorganizationmember: putify(UPDATEORGANIZATIONMEMBER, UPDATEORGANIZATIONMEMBER_URI),
    deleteorganizationmember: deletify(DELETEORGANIZATIONMEMBER, DELETEORGANIZATIONMEMBER_URI),

    // Devices
    getorganizationdevices: getify(GETORGANIZATIONDEVICES, GETORGANIZATIONDEVICES_URI),
    getorganizationdevice: getify(GETORGANIZATIONDEVICE, GETORGANIZATIONDEVICE_URI),
    createorganizationdevice: postify(CREATEORGANIZATIONDEVICE, CREATEORGANIZATIONDEVICE_URI),
    updateorganizationdevice: putify(UPDATEORGANIZATIONDEVICE, UPDATEORGANIZATIONDEVICE_URI),
    deleteorganizationdevice: deletify(DELETEORGANIZATIONDEVICE, DELETEORGANIZATIONDEVICE_URI),

    // Snaps
    createsnap: postify(CREATESNAP, CREATESNAP_URI),
    triggersnap: putify(TRIGGERSNAP, TRIGGERSNAP_URI),

    // Utilities
    sendemail: postify(SENDEMAIL, SENDEMAIL_URI),
    gettingstarted: postify(GETTINGSTARTED, GETTINGSTARTED_URI),

    // Storage
    getallkvs: getify(GETALLKVS, GETALLKVS_URI),
    getallkvheaders: getify(GETALLKVHEADERS, GETALLKVHEADERS_URI),
    createkv: postify(CREATEKV, CREATEKV_URI),
    getkv: getify(GETKV, GETKV_URI),
    deletekv: deletify(DELETEKV, DELETEKV_URI),
    updatekv: putify(UPDATEKV, UPDATEKV_URI),
    getallkvsbytag: getify(GETALLKVSBYTAG, GETALLKVSBYTAG_URI),

    // Neighborhoods
    getmyneighborhoods: getify(GETMYNEIGHBORHOODS, GETMYNEIGHBORHOODS_URI),
    getneighborhood: getify(GETNEIGHBORHOOD, GETNEIGHBORHOOD_URI),
    joinneighborhood: postify(JOINNEIGHBORHOOD, JOINNEIGHBORHOOD_URI),
    getneighbors: getify(GETNEIGHBORS, GETNEIGHBORS_URI),
    getneighbor: getify(GETNEIGHBOR, GETNEIGHBOR_URI),
    getneighborhoodkvs: getify(GETNEIGHBORHOODKVS, GETNEIGHBORHOODKVS_URI),
    getneighborhoodkv: getify(GETNEIGHBORHOODKV, GETNEIGHBORHOODKV_URI),
    createneighborhoodkv: postify(CREATENEIGHBORHOODKV, CREATENEIGHBORHOODKV_URI),
    updateneighborhoodkv: putify(UPDATENEIGHBORHOODKV, UPDATENEIGHBORHOODKV_URI),
    deleteneighborhoodkv: deletify(DELETENEIGHBORHOODKV, DELETENEIGHBORHOODKV_URI),
    createneighborhood: postify(CREATENEIGHBORHOOD, CREATENEIGHBORHOOD_URI),
    deleteneighborhood: deletify(DELETENEIGHBORHOOD, DELETENEIGHBORHOOD_URI),

    // File
    createfile: postify(CREATEFILE, CREATEFILE_URI),
    getfile: getify(GETFILE, GETFILE_URI),
    getmyfiles: getify(GETMYFILES, GETMYFILES_URI),
    getmyfilesbytags: getify(GETMYFILESBYTAGS, GETMYFILESBYTAGS_URI),
    updatefileinfo: putify(UPDATEFILEINFO, UPDATEFILEINFO_URI),
    updatefile: putify(UPDATEFILE, UPDATEFILE_URI),
    deletefile: deletify(DELETEFILE, DELETEFILE_URI),

    // App
    getmyapps: getify(GETMYAPPS, GETMYAPPS_URI),
    getapp: getify(GETAPP, GETAPP_URI),
    createapp: postify(CREATEAPP, CREATEAPP_URI),
    duplicateapp: postify(DUPLICATEAPP, DUPLICATEAPP_URI),
    updateapp: putify(UPDATEAPP, UPDATEAPP_URI),
    deleteapp: deletify(DELETEAPP, DELETEAPP_URI),

    // Anchors
    createanchor: postify(CREATEANCHOR, CREATEANCHOR_URI),
    uploadanchor: putify(UPLOADANCHOR, UPLOADANCHOR_URI),

    // Collaborators
    getappcollaborators: getify(GETAPPCOLLABORATORS, GETAPPCOLLABORATORS_URI),
    createappcollaborator: postify(CREATEAPPCOLLABORATOR, CREATEAPPCOLLABORATOR_URI),
    updateappcollaborator: putify(UPDATEAPPCOLLABORATOR, UPDATEAPPCOLLABORATOR_URI),
    deleteappcollaborator: deletify(DELETEAPPCOLLABORATOR, DELETEAPPCOLLABORATOR_URI),

    // Scenes
    createscene: postify(CREATESCENE, CREATESCENE_URI),
    getscene: getify(GETSCENE, GETSCENE_URI),
    createsceneelement: putify(CREATESCENEELEMENT, CREATESCENEELEMENT_URI),
    updatesceneelementstring: putify(UPDATESCENEELEMENTSTRING, UPDATESCENEELEMENTSTRING_URI),
    updatesceneelementint: putify(UPDATESCENEELEMENTINT, UPDATESCENEELEMENTINT_URI),
    updatesceneelementfloat: putify(UPDATESCENEELEMENTFLOAT, UPDATESCENEELEMENTFLOAT_URI),
    updatesceneelementbool: putify(UPDATESCENEELEMENTBOOL, UPDATESCENEELEMENTBOOL_URI),
    updatesceneelementvec3: putify(UPDATESCENEELEMENTVEC3, UPDATESCENEELEMENTVEC3_URI),
    updatesceneelementcol4: putify(UPDATESCENEELEMENTCOL4, UPDATESCENEELEMENTCOL4_URI),
    deletesceneelement: putify(DELETESCENEELEMENT, DELETESCENEELEMENT_URI),

    // Asset Libraries
    getanasset: getify(GETANASSET, GETANASSET_URI),
    getappassets: getify(GETAPPASSETS, GETAPPASSETS_URI),
    shareassetwithapp: postify(SHAREASSETWITHAPP, SHAREASSETWITHAPP_URI),
    getpersonalassets: getify(GETPERSONALASSETS, GETPERSONALASSETS_URI),
    getpublicassets: getify(GETPUBLICASSETS, GETPUBLICASSETS_URI),
    updateanasset: putify(UPDATEANASSET, UPDATEANASSET_URI),
    deletemyasset: deletify(DELETEMYASSET, DELETEMYASSET_URI),
    promotetostandard: postify(PROMOTETOSTANDARD, PROMOTETOSTANDARD_URI),
    demotetopersonal: postify(DEMOTETOPERSONAL, DEMOTETOPERSONAL_URI),

    // Script Libraries
    getappscripts: getify(GETAPPSCRIPTS, GETAPPSCRIPTS_URI),
    getpersonalscripts: getify(GETPERSONALSCRIPTS, GETPERSONALSCRIPTS_URI),
    getpublicscripts: getify(GETPUBLICSCRIPTS, GETPUBLICSCRIPTS_URI),
    getscript: getify(GETSCRIPT, GETSCRIPT_URI),
    createscript: postify(CREATESCRIPT, CREATESCRIPT_URI),
    updatescript: putify(UPDATESCRIPT, UPDATESCRIPT_URI),
    deletescript: deletify(DELETESCRIPT, DELETESCRIPT_URI),
    sharescriptwithapp: postify(SHARESCRIPTWITHAPP, SHARESCRIPTWITHAPP_URI),

    // Published Apps
    getpublishedapp: getify(GETPUBLISHEDAPP, GETPUBLISHEDAPP_URI),
    getpublishedscene: getify(GETPUBLISHEDSCENE, GETPUBLISHEDSCENE_URI),
    getpublishedassets: getify(GETPUBLISHEDASSETS, GETPUBLISHEDASSETS_URI),
    getpublishedasset: getify(GETPUBLISHEDASSET, GETPUBLISHEDASSET_URI),
    getpublishedappscripts: getify(GETPUBLISHEDAPPSCRIPTS, GETPUBLISHEDAPPSCRIPTS_URI),
    getpublishedscript: getify(GETPUBLISHEDSCRIPT, GETPUBLISHEDSCRIPT_URI),
    searchpublishedapps: getify(SEARCHPUBLISHEDAPPS, SEARCHPUBLISHEDAPPS_URI),
    createmultiplayertoken: postify(CREATEMULTIPLAYERTOKEN, CREATEMULTIPLAYERTOKEN_URI),

    // Spaces
    findspaces: getify(FINDSPACES, FINDSPACES_URI),
    createspace: postify(CREATESPACE, CREATESPACE_URI),
    getspace: getify(GETSPACE, GETSPACE_URI),
    updatespace: putify(UPDATESPACE, UPDATESPACE_URI),
    updatespacevalue: putify(UPDATESPACEVALUE, UPDATESPACEVALUE_URI),
    deletespace: deletify(DELETESPACE, DELETESPACE_URI)
});
